version: "2"
run:
  modules-download-mode: readonly
linters:
  settings:
    nolintlint:
      allow-leading-space: false
    staticcheck:
      checks:
        - all
        # Don't check "Apply De Morgan's law".
        # https://staticcheck.dev/docs/checks/#QF1001
        - -QF1001
        # Don't check "Incorrect or missing package comment".
        # https://staticcheck.dev/docs/checks/#ST1000
        - -ST1000
        # Don't check "Poorly chosen identifier".
        # https://staticcheck.dev/docs/checks/#ST1003
        - -ST1003
  exclusions:
    generated: lax
    rules:
      - linters:
          - const
          - dupl
          - gochecknoglobals
          - goconst
          - golint
          - lll
          - unparam
        path: _test\.go
      - path: (.+)\.go$
        text: Error return value of `(\w+\.)+(Close|CloseSend|Flush|Remove|(Un)?Setenv|(Fp|P)rint(f|ln))\` is not checked
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/datawire github.com/telepresenceio
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
