run:
  modules-download-mode: readonly

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/datawire github.com/telepresenceio
  nolintlint:
    allow-leading-space: false
