name: Build fuseftp on Linux
description: Builds the fuseftp binary on Linux amd64 and arm64
inputs:
  upload:
    default: false
runs:
  using: composite
  steps:
    - name: install dependencies
      shell: bash
      run: |
        brew update
        brew install --cask macfuse
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Make fuseftp-darwin-amd64
      shell: bash
      run: CGO_ENABLED=1 GOARCH=amd64 make fuseftp
    - name: Make fuseftp-darwin-arm64
      shell: bash
      run: CGO_ENABLED=1 GOARCH=arm64 make fuseftp
    - name: Upload binaries
      if: ${{ inputs.upload }}
      uses: actions/upload-artifact@v4
      with:
        name: macos-binaries
        path: build-output/bin
        retention-days: 1
