name: Build fuseftp on Linux
description: Builds the fuseftp binary on Linux amd64 and arm64
inputs:
  upload:
    default: false
runs:
  using: composite
  steps:
    - name: Download winfsp
      shell: bash
      run: |
        curl -L -o winfsp.msi https://github.com/winfsp/winfsp/releases/download/v2.0/winfsp-2.0.23075.msi
    - name: Install winfsp
      shell: powershell
      run: |
        Start-Process msiexec -Wait -verb runAs -Args "/i winfsp.msi /passive /qn /L*V winfsp-install.log"
        [Environment]::SetEnvironmentVariable("Path", "C:\\;C:\\Program Files (x86)\\WinFsp\\inc\\fuse;$ENV:Path", "Machine")
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Make fuseftp-windows-amd64
      shell: bash
      run: CGO_ENABLED=0 make fuseftp
    - name: Make fuseftp-windows-arm64
      shell: bash
      run: CGO_ENABLED=0 GOARCH=arm64 make fuseftp
    - name: Upload binaries
      if: ${{ inputs.upload }}
      uses: actions/upload-artifact@v4
      with:
        name: windows-binaries
        path: build-output/bin
        retention-days: 1
