name: Unit tests
on:
  push:
    branches:
      - master
      - testing
  pull_request:
    types:
      - opened
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run build
        uses: ./.github/actions/build-linux
      - name: Run lint
        run: make lint
      - name: Update /etc/fuse.conf
        run: sudo sh -c 'echo user_allow_other >> /etc/fuse.conf'
      - name: Run tests
        run: make cover
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run build
        uses: ./.github/actions/build-macos
      - name: Run tests
        # We are not currently running the tests on macOS because the brew install doesn't
        # fix the Kext-Loading. The tests must remain disabled until GitHub provides a macOS
        # image with macfuse preinstalled, or some other viable solution pops up.
        # See https://github.com/osxfuse/osxfuse/issues/879#issuecomment-1114140186 for more info
        if: false
        shell: bash
        run: CGO_ENABLED=0 go test ./...
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run build
        uses: ./.github/actions/build-windows
      - name: Run tests
        shell: bash
        run: CGO_ENABLED=0 go test ./...
